http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    host: localhost
    paths: ["/tests", "/tests/:id"]
  api2:
    host: localhost
    paths: ["/ping"]

serviceEndpoints:
  service:
    url: "http://localhost:3000"
  service2:
    url: "http://localhost:3000/"

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: service
              changeOrigin: true
  default2:
    apiEndpoints:
      - api2
    policies:
      - proxy:
          - action:
              serviceEndpoint: service2
              changeOrigin: true
